[pytest]
# Fügt die Verzeichnisse automatisch zum PYTHONPATH hinzu
pythonpath = . personLocator
# Standardmäßig im Ordner 'tests' suchen
testpaths = tests
# Standard-Argumente (v: verbose, s: zeigt print-Ausgaben, ra: zeigt Grund für Skips/Failures)
addopts = -v -s -ra
